### ISSUE TITLE
how to...ideas on...integration with third part attribution svcs?

### ISSUE THREAD

**Issue by sirvon** [BranchMetrics/Branch-Android-SDK#21]
Any guidance, thoughts on hooks these links with existing attribution svcs like
mobileapptracking, appsflyer, and ads networks for more integrated measurement of exsiting
integrations?

thanks
nice stuff!

**Comment by aaustin** [comment]
Hey Sirvon,

Thanks for the kind words - let us know if you have any feedback or suggestions for improvement! And of course, if you refer more devs to the platform, you get one of these awesome hoodies https://branch.io/referral/

Back to your question. We do this with a couple other partners like HotelTonight. The easiest way is to specify the $ios_url/$android_url key with the value of your ad network tracker link. Then, you can use our link in the advertisement and get our link attribution all in one place with the power of the deep links. 

As an alternative, If you have figured out how to do a server to server integration with those guys, we also offer a pretty awesome [web hook](https://github.com/BranchMetrics/Branch-Integration-Guides/blob/master/webhook-guide.md) feature to send all our install and app re-open events back to the endpoint of your choosing. We even bundle in all the referral data so you can do reporting on your own server if you like.

Let me know how I can help!

Best,
Alex

**Comment by sirvon** [comment]
Thanks for the insight.

It seems branch is giving devs back the attribution/event tracking power
thru simplified low/no fee measures.

More doc reading and experimentation is at hand to fully realize this
potential.

Truly thanks for this tool. Immense opportunity with no immediate pricing
barrier!!! Only knowledge necessary.

**Comment by Zhukn1** [comment]
Hi, @aaustin

Is the solution with the $ios_url still valid now, a year later or there is a different way? Will this kind of combined deeplink work also on the second launch?

I'm also trying to figure out how to combine Branch's Deeplink features with AppsFlyer ad networks.

**Comment by Zhukn1** [comment]
oh, sorry.

actually I found a pretty good tutorial in the docs.

https://dev.branch.io/third-party-integrations/ad-network-analytics/overview/

**Comment by sojanpr** [comment]
@Zhukn1 Thanks for reaching out .The solution with $ios_url is still valid. In order to get a faster response could you please send your implementation questions to support@branch.io
