### ISSUE TITLE
Activity recreation issue (configuration change)

### ISSUE THREAD

**Issue by SleeplessByte** [BranchMetrics/Branch-Android-SDK#24]
When changing configurations twice, Branch will spawn the "Trouble initializing Branch. [...]" error, if implemented as documented.

To reproduce: 
`initSession` in an activity `onStart`
`closeSession` in an activity `onStop`

Start the app and rotate twice.

**Comment by aaustin** [comment]
Hey @SleeplessByte,

Let me see if I can reproduce in my testbed - will get back to you with an update

Alex

**Comment by aaustin** [comment]
Goodness gracious - that's bad. I'll roll out a fix today

**Comment by SleeplessByte** [comment]
Perfect! Thank you.

**Comment by SleeplessByte** [comment]
There is a "worse" one:

Relaunch an activity from memory

**Comment by aaustin** [comment]
It's actually supposed to do that! We initialize a new session every single time the app is closed and open to check if it's eligible for new link data. 

Sorry about the fix for rotation as it's fallen by the wayside for some critical capacity increases. It's turned into my weekend project..

**Comment by SleeplessByte** [comment]
@aaustin It's alright. We (EverGive) are waiting on the fix so we can push our update to the store.

I figured it "meant" to do that, but since relaunching something from memory initializes a new session, which also happens when you rotate, `sometimes` the same error appears.

**Comment by aaustin** [comment]
Sorry man - I didn't know you were waiting for it. It looks like have some time tomorrow afternoon to get a fix tested/live. 

From a basic functionality perspective, the links should still work once we resolve the other issue and in my opinion, it shouldn't be blocking a production push. It just causes more inits to be called than ideal.

**Comment by SleeplessByte** [comment]
@aaustin the problem is that if I return from another app, it sometimes won't initialize at all.

**Comment by aaustin** [comment]
@SleeplessByte The fix is coming soon! https://github.com/BranchMetrics/Branch-Android-SDK/pull/26

If you're anxious, you can get the latest JAR from our AWS link:
https://s3-us-west-1.amazonaws.com/branchhost/Branch-Android-SDK.zip

**Comment by SleeplessByte** [comment]
I synched with the current master. Still occurs. Another case to reproduce:

1. Open and init succesfully
2. startActivity( someOtherActivityForExampleADifferentApp )
3. Return (back/context switch/re-open)
4. Branch init error.

**Comment by SleeplessByte** [comment]
The code where the error is spawned is [Branch.java L245-L249].

You are clearing the timer after the error is spawned, might that be backwards?
````Java
if (hasUser() && hasSession() && !installOrOpenInQueue) {
    Log.w( "[branch]", "initUserSessionInternal" );
    if (callback != null)
        callback.onInitFinished(new JSONObject(), new BranchInitError());
    clearCloseTimer();
    keepAlive();
} 
````

**Comment by SleeplessByte** [comment]
Rotation is fixed on master. 

Now testing leave app, return to app.

**Comment by SleeplessByte** [comment]
I renamed this so it can be closed. Standing issues in #30
