### ISSUE TITLE
Branch links don't expand on Android

### ISSUE THREAD

**Issue by SleeplessByte** [BranchMetrics/Branch-Android-SDK#25]
Might be related to #24

The URL `https://bnc.lt/l/2enuGxU-2g` resolves.
`evgbr://open?link_click_id=81743897969033762` but only fills in `referringParams` on iOS, not Android.

To reproduce:

- Clean app open after app is killed using the link
- Get Branch Instance
- Set Identity (if any)
- Init session with `BranchReferralInitListener`, `Activity#getIntent#getData`, `Activity`

Below the lines from the log showing the problem
````
I/Evergive﹕ [1] 2.onInitFinished: [branch-behavior] initialization finished for evgbr://open?link_click_id=81743897969033762
V/Evergive﹕ [1] BranchMetricsBehavior.handleBranchLink: [branch-behavior] error: null, referringParams: {}
````

**Comment by aaustin** [comment]
It's possible that the session was not closed prior to clicking the link - are you calling closeSession in onStop still? So you received parameter from a prior session. This is a pretty common integration mistake

**Comment by SleeplessByte** [comment]
Yes. Close session is always called when the app is closed/moves to background

````
V/Evergive﹕ [1] BranchMetricsBehavior.onAction: [branch-behavior] ACTION: CLOSE SESSION
````

That said, please keep in mind that this would fail either way if the App is killed, if you only rely on `closeSession`.

**Comment by SleeplessByte** [comment]
By the way, if I received a parameter from a prior session, should I not see the Branch data from that session (e.g. a previous link?).

**Comment by SleeplessByte** [comment]
Actually, I think I managed to get it working on the debug build. I'll close this out and see what the difference is.

**Comment by SleeplessByte** [comment]
The problem was that the links where always opened in the production build (matches the package). Opening the development build manually after the production build opened, correctly loaded the branch data.

**Comment by aaustin** [comment]
Ah thanks for closing the issue. I'll get back to you on the other one later today, but I don't think you should hold a production release for it. It's unnoticeable to the customer

**Comment by SleeplessByte** [comment]
@aaustin should we never show and error from branch to the user?

**Comment by aaustin** [comment]
Probably not, but it kind of depends on the implementation. If an error is thrown in getShortUrl, we automatically return a default URL with no parameters. If an error is throw in init, we recommend just not processing the callback.
