### ISSUE TITLE
UTF-8 character "filtering"

### ISSUE THREAD

**Issue by SleeplessByte** [BranchMetrics/Branch-Android-SDK#29]
[This line](https://github.com/BranchMetrics/Branch-Android-SDK/blob/master/Branch-SDK/src/io/branch/referral/Branch.java#L968) tries to filter out bad parameter values. 

- If you download this repository on Windows, the file will be mangled and show � instead of Õ. As far as I know Android itself [doesn't support converting this](http://stackoverflow.com/questions/16786739/how-to-use-unicode-in-android-resource) from unicode notation either. 
- I think the filtering itself is limited. If you want to retain the user data, consider [base64-url-safe encoding](http://tools.ietf.org/html/rfc4648#section-5). I might want to keep new lines, right?
- Is there a reason that only this character (apart from the newlines and carriage returns) is filtered?

("same" as #23)

**Comment by aaustin** [comment]
I removed this filter in the latest build and added a backlog task to migrate over base64 encoding. Thanks for the suggestion!

**Comment by SleeplessByte** [comment]
Super!
