### ISSUE TITLE
Session can't be closed when links are just created

### ISSUE THREAD

**Issue by SleeplessByte** [BranchMetrics/Branch-Android-SDK#30]
````
V/Evergive﹕ [1] BranchMetricsBehavior.onAction: [branch-behavior] ACTION: SEND INVITE
V/[branch]﹕ processing queue so keep alive
V/[branch]﹕ hook onto life support
I/BranchSDK﹕ posting to https://api.branch.io/v1/url
I/BranchSDK﹕ Post value = {"tags":["version1","android","group"],"session_id":"86226031148532384","device_fingerprint_id":"82715523476882253","identity_id":"82715523510436686","data":"{ [.. data ..] }"
I/BranchSDK﹕ returned {"url":"https://bnc.lt/l/2mJYRLU-1q"}
D/Evergive﹕ [28282] InvitationTextApi.notify: [invitation-text-api] code: 200
I/Timeline﹕ Timeline: Activity_launch_request id:com.hipchat time:225768382
V/Evergive﹕ [1] BranchMetricsBehavior.onAction: [branch-behavior] ACTION: CLOSE SESSION
V/[branch]﹕ not closing: keep alive
V/[branch]﹕ unplug from life support
````

````
V/Evergive﹕ [1] BranchMetricsBehavior.onAction: [branch-behavior] ACTION: INIT SESSION null
V/[branch]﹕ init user session (internal)
V/[branch]﹕ init with user and session - nothing open in queue
I/Evergive﹕ [1] 1.onInitFinished: [branch-behavior] initialization finished for null
````

- When a branch link is to be created, Branch is kept alive (hooked onto life support). 
- When the callback launches an activity, it's still hooked onto life support, and isn't unplugged until the next Activity is already started (`Timeline`)
- When returning to the activity, the session was never closed, thus branch is not called.

Proposed resolution: `keepAlive_` when the link is created or when the callback is called.

Use case:
1. Select share intent
2. Create link and follow intent
3. Test my own link
4. Re-opens app
5. Should be a new session

**Comment by aaustin** [comment]
I'll be in the train in about an hour and a half and can address this one then. Sorry for the delay

**Comment by SleeplessByte** [comment]
Any luck?

**Comment by aaustin** [comment]
@SleeplessByte I believe this should resolve it (per your suggestion) https://github.com/BranchMetrics/Branch-Android-SDK/commit/628276cb481c3c74e35ce0ee62ae150fed820eb3

**Comment by SleeplessByte** [comment]
I'll test it out right away.

**Comment by SleeplessByte** [comment]
:+1:
