### ISSUE TITLE
gradle project dependency

### ISSUE THREAD

**Issue by sreereddymenon** [BranchMetrics/Branch-Android-SDK#42]
Hello Branch Team,
 
 Loved your Product . As everybody moving to android studio. It would be better if you can add a gradle dependency on documention . 

dependencies {
    compile '........'
}
Thanks

**Comment by qinweigong** [comment]
Hi @sreereddymenon ,

Thanks for supporting our product!
Yes, we are just shifting to gradle for our Android SDK.

https://oss.sonatype.org/#nexus-search;quick~io.branch.sdk.android

We are working on the documentation now. Will update you once it's done.

Thanks,

Qinwei
