### ISSUE TITLE
errors in importing Branch-Android-SDK-TestBed

### ISSUE THREAD

**Issue by MrYogi** [BranchMetrics/Branch-Android-SDK#48]
Error:Android Dex: [Branch-SDK-TestBed] Unable to execute DX
Error:Android Dex: [Branch-SDK-TestBed] com.android.dex.DexException: Multiple dex files define Lio/branch/referral/ApkParser;
Error:Android Dex: [Branch-SDK-TestBed] at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Error:Android Dex: [Branch-SDK-TestBed] at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Error:Android Dex: [Branch-SDK-TestBed] at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Error:Android Dex: [Branch-SDK-TestBed] at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Error:Android Dex: [Branch-SDK-TestBed] at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Error:Android Dex: [Branch-SDK-TestBed] at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
Error:Android Dex: [Branch-SDK-TestBed] at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
Error:Android Dex: [Branch-SDK-TestBed] at com.android.dx.command.dexer.Main.run(Main.java:246)
Error:Android Dex: [Branch-SDK-TestBed] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:Android Dex: [Branch-SDK-TestBed] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
Error:Android Dex: [Branch-SDK-TestBed] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:Android Dex: [Branch-SDK-TestBed] at java.lang.reflect.Method.invoke(Method.java:606)
Error:Android Dex: [Branch-SDK-TestBed] at org.jetbrains.android.compiler.tools.AndroidDxRunner.runDex(AndroidDxRunner.java:161)
Error:Android Dex: [Branch-SDK-TestBed] at org.jetbrains.android.compiler.tools.AndroidDxRunner.main(AndroidDxRunner.java:294)
Error:Android Dex: [Branch-SDK-TestBed] at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:121)

**Comment by qinweigong** [comment]
@MrYogi Hmm, weird. We've never seen this before. Just did some googling and found this
http://stackoverflow.com/questions/7870265/unable-to-execute-dex-multiple-dex-files-define-lcom-myapp-rarray

Could you please give it a try, and let me know if it fixes the problem?

Thanks a lot,

Qinwei

**Comment by MrYogi** [comment]
nevermind, i started from scrap, added all classes from your sample, now working fine,

thanks
