### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by 3rdstonejubin** [BranchMetrics/Branch-Android-SDK#70]
java.util.ConcurrentModificationException
at java.util.LinkedList$LinkIterator.next(LinkedList.java:124)
at io.branch.referral.ServerRequestQueue$1.run(ServerRequestQueue.java:52)
at java.lang.Thread.run(Thread.java:841)

Branch SDK version: 1.3.8
Android version: 4.3
Device: Hydro LIFE (C6530N)

**Comment by qinweigong** [comment]
Hi @3rdstonejubin,

Thanks for reaching out with the info! Really appreciate it!

I believe our more recent Android SDK version should have fixed this issue. Please update to the latest v1.5.5. Let us know if you still see this crash.

Thanks,

Qinwei

**Comment by sojanpr** [comment]
We have made a lot of changes to fix the threading issue on the SDK  with release v1.6.0. Please update to v1.6.0
