### ISSUE TITLE
Please upload sources to maven central

### ISSUE THREAD

**Issue by tadas-subonis** [BranchMetrics/Branch-Android-SDK#72]
Hi,

would it be possible to upload sources of the Branch SDK so it would be easier to inspect code in SDK? It would help a lot as Android Studio would download that automatically and I wouldn't need to get them separately from GitHub.

In maven it's done with http://central.sonatype.org/pages/apache-maven.html#javadoc-and-sources-attachments 

For gradle: http://central.sonatype.org/pages/gradle.html#jar-files

Thanks

**Comment by aaustin** [comment]
@tadas-subonis Thanks so much for the suggestion. We'll look into getting this done as soon as possible. I'll let you know after it's done.

**Comment by sojanpr** [comment]
@tadas-subonis  Thanks for your suggestion. We have added the Source and JavaDocs to maven. You can find them under
"https://repo1.maven.org/maven2/io/branch/sdk/android/library/1.5.5/"
For Android studio adding gradle dependency   "compile 'io.branch.sdk.android:library:1.5.0'"  you should be able to inspect the code. Please let us know if you still have issue.

**Comment by tadas-subonis** [comment]
Thanks! It will make things a lot easier.
